### ISSUE TITLE
Incorporate new API throttling

### ISSUE THREAD

**Issue by rdohms** [rdohms/meetup-api-client#3]
Add a plugin to handle the API rate limiting system used by Meetup.com

**Comment by stevelacey** [comment]
If anyone's interested, I finally implemented an albeit basic solution, by simply wrapping the client class and interogating all responses and sleeping then nearing the limit: https://github.com/phpsw/phpsw/blob/develop/src/Meetup/API/Client.php

**Comment by rdohms** [comment]
This is also solved by the patch in PR #19

**Comment by rdohms** [comment]
Implemented in #19 and accepted for v2.
