### ISSUE TITLE
BC break - GetEvent removed in 2.2

### ISSUE THREAD

**Issue by pavlakis** [rdohms/meetup-api-client#41]
With v2.2 [GetEvent has been removed](https://github.com/rdohms/meetup-api-client/commit/ebbe87b3dbfa30d88bb5046e54b90b4ffbfbfb38)

Is there an alternative call?

**Comment by rdohms** [comment]
@pavlakis this is due to it being deprecated by Meetup, as you can see here: https://www.meetup.com/meetup_api/docs/2/event/#get

It was replaced by `getGroupEvents`.

This is indeed a BC, but its been a long time since release, so i'll leave the releases as they are.
